heatHBack/pom.xml, heatHBack/src/main/java/heatH/heatHBack/config/SecurityConfig.java, heatHBack/src/main/java/heatH/heatHBack/controller/AuthController.java, heatHBack/src/main/java/heatH/heatHBack/model/User.java, heatHBack/src/main/java/heatH/heatHBack/model/request/RefreshTokenRequest.java, heatHBack/src/main/java/heatH/heatHBack/model/response/AuthResponse.java, heatHBack/src/main/java/heatH/heatHBack/service/IAuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/CustomUserDetailsService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/JwtService.java, heatHBack/src/main/resources/application.yaml
=> Add refresh token

heatHBack/pom.xml, heatHBack/src/main/java/heatH/heatHBack/controller/AuthController.java, heatHBack/src/main/java/heatH/heatHBack/model/UserMailVerification.java, heatHBack/src/main/java/heatH/heatHBack/model/request/EmailRequest.java, heatHBack/src/main/java/heatH/heatHBack/repository/UserVerificationRepository.java, heatHBack/src/main/java/heatH/heatHBack/service/IAuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/MailService.java, heatHBack/src/main/resources/application.yaml
Adding mailing service and merging into main branch
=> Add mailing service

heatHBack/src/main/java/heatH/heatHBack/controller/FeedController.java, heatHBack/src/main/java/heatH/heatHBack/model/Feed.java, heatHBack/src/main/java/heatH/heatHBack/model/FeedType.java, heatHBack/src/main/java/heatH/heatHBack/model/request/FeedRequest.java, heatHBack/src/main/java/heatH/heatHBack/repository/FeedRepository.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/FeedService.java
Adding feed service and merging into main branch
=> Add Feed Service

heatHBack/src/main/java/heatH/heatHBack/controller/InterestFormController.java, heatHBack/src/main/java/heatH/heatHBack/model/InterestForm.java, heatHBack/src/main/java/heatH/heatHBack/model/request/InterestFormRequest.java, heatHBack/src/main/java/heatH/heatHBack/repository/InterestFormRepository.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/InterestFormService.java
Add interest form and merge into main branch
=> Add Interest Form

heatHFront/React-Web/web/package-lock.json, heatHFront/React-Web/web/src/App.js, heatHFront/React-Web/web/src/components/Template.js, heatHFront/React-Web/web/src/pages/HomePage.js, heatHFront/React-Web/web/src/pages/LandingPage.jsx, heatHFront/React-Web/web/src/pages/Login/SignIn.tsx, heatHFront/React-Web/web/src/pages/Login/SignupPage.jsx, heatHFront/React-Web/web/src/pages/SavedRecipes.js
- **New** MUI-based `/signin` form posting to `authService.login`
- **Error handling**: shows server errors or “Login failed” fallback
- **Redirect** to `/home` on success (`useNavigate`)
- **Links**: includes “Forgot Password?” and “Sign Up”
- **Routing**: registered `/signin` route in `App.js`
=> Fixed visual bugs and added routes for authentication.

heatHFront/React-Web/web/src/pages/SavedRecipes.js
Added the "add new recipe seciton" to the saved recipes page
=> [UI]: Add section for new recipes in saved recipe page

heatHBack/src/main/java/heatH/heatHBack/model/InterestForm.java, heatHBack/src/main/java/heatH/heatHBack/model/request/InterestFormRequest.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/InterestFormService.java
Add gender and profile photo features for user forms.
=> Backend : Add gender and profile photo to the form.

heatHFront/React-Web/web/src/App.js, heatHFront/React-Web/web/src/pages/HomePage.js, heatHFront/React-Web/web/src/pages/RecipeDetail.js, heatHFront/React-Web/web/src/pages/SavedRecipes.js, heatHFront/React-Web/web/src/services/recipeService.js
Added separate recipe pages for each recipe instead of a dialogue window and added recipeService.js for recipe management.
=> [UI] + [Feature]: Add recipe detail page and service for recipe management

heatHBack/src/main/java/heatH/heatHBack/controller/RecipeController.java, heatHBack/src/main/java/heatH/heatHBack/repository/RecipeRepository.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/RecipeService.java
Save it to database, 
please test the functions
=> Backend : Add photo feature to Recipe Service,

heatHBack/src/main/java/heatH/heatHBack/model/SavedRecipe.java, heatHBack/src/main/java/heatH/heatHBack/model/response/SavedRecipeResponse.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/SavedRecipeService.java
Add title and photo to saved recipes
=> Update Saved Recipes

heatHBack/pom.xml, heatHBack/src/main/java/heatH/heatHBack/service/implementation/MailService.java
Remove smtp connections because DigitalOcean does not allow smtp connections anymore.
=> Backend : Add SendGrid API for sending mails.

heatHBack/src/main/java/heatH/heatHBack/controller/AuthController.java, heatHBack/src/main/java/heatH/heatHBack/model/request/VerificationRequest.java, heatHBack/src/main/java/heatH/heatHBack/service/IAuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java
=> Backend : Fix mailing errors

heatHBack/src/main/java/heatH/heatHBack/model/request/RecipeRequest.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/RecipeService.java
Add total calory field to recipe
Add price field to recipe
=> Backend : Add some features to Recipe Service

heatHBack/src/main/java/heatH/heatHBack/controller/AuthController.java, heatHBack/src/main/java/heatH/heatHBack/repository/UserRepository.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java, heatHFront/React-Web/web/src/pages/ForgotPasswordPage.jsx, heatHFront/React-Web/web/src/pages/Login/SignupPage.jsx, heatHFront/React-Web/web/src/pages/ResetPasswordPage.jsx, heatHFront/React-Web/web/src/services/authService.js
Added mail forwarding connection for sign-up and forgot password pages.
Written an endpoint to check if the mail exists in the db.
=> Password verification, API integration

heatHFront/React-Web/web/src/components/ProtectedRoute.tsx, heatHFront/React-Web/web/src/pages/InitialProfileSetup.js
Added a new controller that checks if it is users first login and prompts the form accordingly.
The controller restricts user from leaving the form if not filled.
=> Made sure that the user must fill the form before entering the site at first login

heatHBack/src/main/java/heatH/heatHBack/controller/AuthController.java, heatHBack/src/main/java/heatH/heatHBack/model/request/ResetPasswordRequest.java, heatHBack/src/main/java/heatH/heatHBack/service/IAuthService.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/AuthService.java, heatHFront/React-Web/web/src/pages/ResetPasswordPage.jsx
Implement password reset functionality
=> [BackEnd]: Implement password reset functionality

heatHFront/React-Web/web/src/pages/ResetPasswordPage.jsx
Refactor ResetPasswordPage to remove unused token handling and update API endpoint
=> [UI/BUG-FIX]: Refactor ResetPasswordPage to remove unused token handling and update API endpoint

heatHBack/src/main/java/heatH/heatHBack/service/implementation/FeedService.java
Add Recipe Details to recent feeds because it will be using in frontend
=> [Backend] : Add Recipe Details to FeedResponse

heatHBack/src/main/java/heatH/heatHBack/model/Feed.java
=> [Backend] : Delete Likes field because it is redundant.

heatHFront/React-Web/web/src/pages/HomePage.js, heatHFront/React-Web/web/src/pages/SavedRecipes.js, heatHFront/React-Web/web/src/pages/myRecipes.js
- Added feed fetching and liking functionality to HomePage.
- Implemented optimistic UI updates for feed likes.
- Improved form validation in MyRecipes to ensure all fields are filled before submission.
- Updated SavedRecipes to include copy link functionality and improved error handling.
- Refactored API calls to use recipeService for better organization.
=> Enhance HomePage and MyRecipes with feed functionality and form validity.

heatHBack/src/main/java/heatH/heatHBack/service/implementation/FeedService.java
=> [Backend] : Add image property to feedresponse

heatHBack/src/main/java/heatH/heatHBack/service/implementation/FeedService.java
Added new features to getByUser function
=> [Backend] : Add new features to myfeeds

heatHFront/React-Web/web/src/pages/HomePage.js, heatHFront/React-Web/web/src/services/feedService.js
- Added responsive like and bookmark to the comment pop-up
- Created a pop-up for the comment section.
- Connected the comment feed to the endpoint. 
- Connected the commenting to the endpoint.
- Comments of other users are added to the UI.
=> Homepage add comment

heatHBack/src/main/java/heatH/heatHBack/controller/FeedController.java, heatHBack/src/main/java/heatH/heatHBack/model/response/FeedProfileResponse.java, heatHBack/src/main/java/heatH/heatHBack/service/implementation/FeedService.java
[Backend] : Add name surname and profile photo field to default response. Change feed list.
=> Feed other users

heatHFront/React-Web/web/src/pages/HomePage.js
=> Add comment count display on HomePage for each feed item

heatHFront/React-Web/web/src/pages/HomePage.js
Paginating added. Homepage failed if this commit is not included in the branch.
=> !!!URGENT!!! Implement infinite scrolling on HomePage with pagination support

heatHFront/React-Native-Mobile/app/(main)/profile.jsx, heatHFront/React-Native-Mobile/services/interestFormService.js
- added editing option in profile tab
=> profile data is editable
